version: '2'
services:
    lb:
        image: dockercloud/haproxy
        links:
            - web
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock 
    web:
        build: .
        links: 
            - redis
        ports:
            - 8080
    redis:
        image: redis:latest